### Consider the below code to answer further questions:

#### import numpy as np
#### list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#### array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [ ]:
import numpy as np

In [ ]:
list_ = [ '1', '2', '3', '4', '5']
array_list = np.array(object = list_)

In [ ]:
type(list_)

In [10]:
type(array_list)

numpy.ndarray

Yes, the datatypes of variables list_ and array_list are different.

list_ is a variable of datatype 'list' and array_list is a variable of datatype numpy array (2D)

### Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [14]:
# Datatype of each element of the variable list_
for i in list_:
    print (type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [15]:
# Datatype of each element of the variable array_list
for arr in array_list:
    print (type(arr))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3.Considering the following changes in the variable, array_list:
#### array_list = np.array(object = list_, dtype = int)

#### Will there be any difference in the data type of the elements present in both the variables, list_ and
#### array_list? If so then print the data types of each and every element present in both the variables, list_
#### and array_list.

In [16]:
array_list = np.array(object = list_, dtype = int)

In [17]:
type(array_list)

numpy.ndarray

In [18]:
type(list_)

list

In [19]:
# Datatype of each element of the variable list_
for i in list_:
    print (type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [20]:
# Datatype of each element of the variable array_list
for arr in array_list:
    print (type(arr))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Yes, there is a difference in each and every elements of the variable array_list.
Previously, the datatype of every element of array_list was 'numpy.str_'

But post changes in the variable, array_list, the datatype of every element in the variable now becomes 'numpy.int64'

### Consider the below code to answer further questions:

#### import numpy as np
#### num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#### num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [22]:
import numpy as np

In [23]:
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object = num_list)

In [26]:
print(num_array)

[[1 2 3]
 [4 5 6]]


In [24]:
num_array.shape

(2, 3)

In [25]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.

In [27]:
import numpy as np

# create a 3x3 matrix filled with zeros
matrix = np.zeros((3,3))

In [28]:
matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Q6. Create an identity matrix of shape (5,5) using numpy functions?

In [29]:
import numpy as np

# create a 5x5 identity matrix
matrix = np.identity(5)

In [30]:
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])